//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string imageUrl { get; set; }
        public string videoUrl { get; set; }
        public int categoryId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
